global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'quiz-app'
    environment: 'production'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'quiz-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['YOUR_CLOUD_RUN_URL']  # Update after deployment
        labels:
          app: 'quiz-app'

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['YOUR_JENKINS_IP:8080']  # Update with Jenkins IP